import type { Metadata } from "next";
import localFont from "next/font/local";
import React, { useState } from "react";
import { Menu, Bell, ChevronDown, ChevronUp } from "lucide-react";
import Sidebar from "./components/DashboardSidebar";
import "./globals.css";
import DashboardHeader from "./components/DashboardHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-min flex bg-[#f7f7f7]">
          <aside className="w-56  shadow-md p-4 flex flex-col">
            <div className="mb-8 flex justify-center items-center gap-2">
              <p className="bg-gradient-to-r from-orange-400 to-red-500 rounded-xl px-2 py-1">logo</p>
              <h1 className="text-2xl font-bold ">Billswift</h1>
            </div>
            <button className="bg-gradient-to-r from-orange-400 to-red-500 text-white rounded-3xl py-2 px-4 mb-6">+ New</button>
            <Sidebar />
          </aside>

          <main className="flex-grow overflow-auto bg-[#f3f3e0]">
            <header className="shadow-sm">
              <div className=" p-4 flex justify-between items-center">
              <div className="flex items-center space-x-3">
                <Menu className="text-black" />
                  <img src="https://media.licdn.com/dms/image/v2/D4E0BAQG_jZUR-cUjog/company-logo_200_200/company-logo_200_200/0/1709292373135/nexular_corp_logo?e=1735776000&v=beta&t=L4mUZftbxUWYlcaJoHq7Gid7QsRLpazLPybUgp0gzCI" alt="" className=" rounded-2xl w-16"/>
                <p className="text-lg">Welcome back! <span className="font-bold">Nexular Corp</span></p>
              </div>
              <div className="flex items-center space-x-4">
                <DashboardHeader />
              </div>

              </div>
            <div className="flex items-center text-lg space-x-4 mx-5">
              <span className="font-bold border-b-4 border-red-500 border-">Home</span>
              <span className="text-gray-500">Cash flow</span>
              </div>
            </header>
            <div>
            </div>

            <div className="flex flex-wrap gap-4 p-4">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
